#  Will create a 1 node cluster.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  # specific to kind to access this ports
  extraPortMappings:
  - containerPort: 5432
    hostPort: 5433
  - containerPort: 4000
    hostPort: 4000
  - containerPort: 3000
    hostPort: 3000
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP